/*
 * This source file was generated by the Gradle 'init' task
 */
package RushHour;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import javax.swing.JPanel;

class AppTest {
    @Test void appHasAGreeting() {
        var classUnderTest = new RushHourGame(new JPanel());
        assertNotNull(classUnderTest.generateGamePieces(), "app should be able to generate game pieces");
    }
}
